/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export const LUXE_EVOLUPTE_PROMPTS: Record<string, string> = {
  luxe_boutique: "À travers la vitrine immaculée d'une boutique de luxe, le sujet est capturé dans un instant de contemplation. Les reflets dorés de l'enseigne (Dior, Chanel) dansent sur son visage tandis que la lumière douce de l'intérieur sculpte sa silhouette, créant une scène d'élégance urbaine et feutrée.",
  luxe_rue: "Le sujet marche d'un pas assuré sur les pavés de l'Avenue Montaigne. Un rayon de soleil perce entre les immeubles haussmanniens, créant un contre-jour subtil. La caméra capture le mouvement fluide de son manteau et le reflet d'une vitrine de luxe dans ses lunettes de soleil.",
  luxe_hotel: "Un instant suspendu dans le bar feutré d'un palace. Le sujet, assis dans un fauteuil en velours profond, fait tourner la glace dans son verre. La lumière chaude d'une lampe de designer se reflète sur le cristal, tandis qu'à l'extérieur, les lumières de la ville scintillent à travers la baie vitrée.",
  luxe_studio_photo: "Dans le silence d'un studio photo au fond beige infini, le sujet prend une pose sculpturale. L'éclairage principal, une large softbox, enveloppe sa peau d'une lumière douce et parfaite, tandis qu'un second projecteur dessine un léger halo sur ses cheveux. L'objectif est de mettre en avant la texture d'un bijou ou d'une montre.",
  luxe_soiree: "Au milieu d'une soirée de gala animée, la caméra isole le sujet sur un rooftop surplombant la ville. Le vent fait légèrement bouger sa robe de soirée. En arrière-plan, les lumières de la ville sont un bokeh scintillant. Il ou elle esquisse un sourire énigmatique, une coupe de champagne à la main.",
  luxe_dior: "Dans un escalier en marbre d'un hôtel particulier parisien, le sujet descend lentement, sa robe de bal en satin bruissant à chaque pas. La lumière ivoire d'un lustre en cristal crée des reflets magiques sur le tissu et met en valeur un flacon de parfum posé sur une console.",
  luxe_chanel: "Une composition en noir et blanc intemporelle. En studio, le sujet, vêtu d'un simple tailleur en tweed, ajuste un collier de perles. La lumière, inspirée du cinéma classique, sculpte son visage avec une grande douceur, créant une image d'une élégance sobre et puissante.",
  luxe_louis_vuitton: "L'instant capturé sur le quai d'une gare rappelant l'Orient Express. Le sujet, impeccable dans son trench-coat, pose une main sur une malle de luxe en cuir monogrammé. La vapeur d'un train qui s'apprête à partir enveloppe la scène d'une atmosphère de voyage et d'aventure.",
  luxe_cartier: "Un macro-plan cinématique. La caméra se concentre sur la main du sujet, ornée d'une bague iconique, qui se pose délicatement sur un tissu de velours rouge. La lumière chaude et précise fait scintiller chaque facette de la pierre et chaque détail du métal précieux.",
  luxe_hermes: "La scène se déroule dans une écurie de luxe aux boiseries impeccables. La lumière douce du matin filtre à travers une fenêtre. Le sujet, vêtu simplement mais avec une élégance naturelle, ajuste une selle en cuir ou noue un carré de soie autour de son cou.",
  luxe_rolex: "Gros plan sur le poignet du sujet, où une montre de luxe capte la lumière. En arrière-plan, le décor est en mouvement mais flou : le cockpit d'un avion, le volant d'une voiture de sport sur une route de montagne. L'accent est mis sur la précision et l'action.",
  luxe_patek_philippe: "Dans une bibliothèque privée aux murs lambrissés, un père (le sujet) montre le mécanisme de sa montre à son fils. C'est un moment de transmission, intime et chaleureux. La lumière est douce, tamisée, accentuant le sentiment d'héritage et de tradition.",
  luxe_audemars: "Le sujet se tient devant une œuvre d'art contemporain aux lignes géométriques. Sa montre, au design audacieux, est mise en valeur par un éclairage de galerie, froid et précis. La scène évoque la modernité, l'architecture et la performance.",
  luxe_jaeger: "Dans un atelier d'horloger minimaliste et épuré, la caméra fait un focus extrême sur la pureté du design d'une montre posée sur un établi. La lumière est presque clinique, révélant la perfection de chaque détail, tandis que la main de l'horloger (le sujet) entre à peine dans le cadre.",
  luxe_gucci: "Une scène excentrique et colorée dans une villa romaine décadente. Le sujet, avec une attitude provocante et androgyne, est allongé sur un canapé baroque, entouré d'objets incongrus. La lumière est dure, presque crue, avec un grain de film prononcé.",
  luxe_prada: "Le sujet marche dans un couloir à l'architecture brutaliste, créant un contraste saisissant entre la fluidité de sa tenue et la rigueur du décor. La lumière est froide et géométrique, projetant des ombres longues et nettes. L'ambiance est intellectuelle et distante.",
  luxe_versace: "Une fête opulente au bord d'une piscine. Le sujet, au centre de l'attention, porte une tenue audacieuse aux motifs baroques et dorés. La lumière chaude du coucher de soleil se mêle aux flashs des photographes, créant une scène de glamour exubérant et sans complexe.",
  luxe_fendi: "Scène de rue élégante à Milan. Le sujet, portant un manteau aux coupes impeccables, est surpris dans un moment de vie quotidienne, comme acheter des fleurs ou héler un taxi. La lumière est naturelle et douce, l'ambiance est celle d'un luxe discret et contemporain.",
  luxe_balmain: "Une vision de puissance urbaine et nocturne. Le sujet, en veste à épaulettes structurée, se tient sur un pont surplombant les lumières de la ville. Les reflets métalliques de sa tenue captent les néons, créant une silhouette forte et graphique.",
  luxe_bulgari: "Sur une terrasse surplombant la mer Méditerranée, la peau du sujet est dorée par la fin de journée. La caméra se rapproche d'un bijou spectaculaire qui capte les derniers rayons du soleil, créant un éclat éblouissant. L'ambiance est sensuelle et précieuse.",
  luxe_tiffany: "Devant la vitrine d'une boutique sur la 5ème Avenue à New York, tôt le matin. La rue est encore déserte. Le sujet, élégant et rêveur, contemple les bijoux. La lumière est claire, presque cristalline, dans les tons bleutés iconiques de la marque.",
  luxe_moncler: "Au sommet d'une montagne enneigée, mais dans un contexte de luxe. Le sujet, dans une doudoune couture, se tient près d'un chalet d'architecte. La lumière vive du soleil sur la neige crée un contraste saisissant, mêlant sport, nature et design.",
  luxe_element_feu: "Gros plan sur un bijou en or qui capte les reflets dansants d'une cheminée de palace. En arrière-plan, le sujet au visage à moitié dans l'ombre contemple les flammes, créant une atmosphère intime et sensuelle.",
  luxe_element_eau: "La caméra suit des gouttes d'eau qui perlent sur la peau du sujet sortant d'un spa de luxe. Une autre scène capture le reflet déformé d'une voiture de luxe dans une flaque d'eau après une averse nocturne sur une place parisienne.",
  luxe_element_air: "Sur un rooftop, le vent soulève avec élégance les pans d'un foulard en soie ou d'une robe vaporeuse. Le sujet ferme les yeux, comme pour sentir la caresse de l'air. L'arrière-plan est un ciel immense, créant une sensation de liberté et d'espace.",
  luxe_element_terre: "Focus sur la texture d'un sac en cuir grainé posé sur un rocher brut dans un paysage désertique. Le sujet, en tenue d'explorateur chic, regarde l'horizon. Les tons sont chauds, terreux (ocre, beige, brun), évoquant l'authenticité et l'aventure.",
};