/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

// This file contains the full, detailed data for the "Fighter Pilot" story library.
// It's used by the PilotLibrary component to display searchable scene information.

export interface PilotScene {
    id: string;
    title: string;
    summary: string;
    description: string;
    tags: string[];
    vehicles?: string[];
    props?: string[];
    camera?: { type: string; note: string }[];
    duration_est?: number;
    lines?: string[];
    checklist?: string[];
}

export interface PilotLibraryData {
    meta: {
        title: string;
        version: string;
        author: string;
        description: string;
    };
    scenes: PilotScene[];
}


export const PILOTS_LIBRARY_DATA: PilotLibraryData = {
  "meta": {
    "title": "Librairie Pilotes de Chasse — Version Intégrale 2025",
    "version": "2025.10.05",
    "author": "Generated by ChatGPT for Yann",
    "description": "Scènes, plans et métadonnées pour storyboard / UI / génération d'images"
  },
  "scenes": [
    {
      "id": "s01-arrivee-checkpoint",
      "title": "Arrivée à la base — Checkpoint",
      "summary": "Arrivée des pilotes : muscle car, moto, 4x4. Checkpoint, contrôle d'identité.",
      "description": "Matin sec, lumière dorée. Les véhicules arrivent. Contrôle au checkpoint, mécanos notent les plaques. Sons moteurs, drapeaux qui claquent.",
      "tags": ["arrivée","véhicules","checkpoint","ambiance-matin"],
      "vehicles": ["muscle_car","moto","4x4","van_militaire"],
      "props": ["plaques_identite","sacs_de_vol","gants"],
      "camera": [
        {"type":"wide","note":"plan d'ensemble tarmac, véhicules entrant"},
        {"type":"detail","note":"main qui passe la carte d'identité"},
        {"type":"tracking","note":"suivi d'une moto qui vient s'arrêter"}
      ],
      "duration_est": 45
    },
    {
      "id": "s02-vestiaire-preparation",
      "title": "Vestiaires — Préparation",
      "summary": "Préparation des pilotes : en sous-vêtements, plaques visibles, enfilage combinaison anti-G.",
      "description": "Bancs, odeur de cuir et de détergent. Geste méthodique. Casques posés côté, visières relevées. Sens du rituel.",
      "tags": ["vestiaire","costume","rituel","intime"],
      "props": ["combinaison_antiG","bottes_zippées","casque","plaque_id"],
      "camera": [
        {"type":"medium","note":"plan sur plusieurs pilotes en train d'enfiler leur combinaison"},
        {"type":"close","note":"gros plan sur plaque d'identité et tatouage discret"}
      ],
      "duration_est": 60
    },
    {
      "id": "s03-briefing-capitaine",
      "title": "Briefing — Le Capitaine",
      "summary": "Salle de briefing. Carte tactique, instructions, fenêtre temporelle.",
      "description": "Ecran tactique, voix posée du capitaine, mention radio en alpha-seven. Ambiance concentrée.",
      "tags": ["briefing","commandement","tactique"],
      "props": ["ecran_tactique","carte_mission","tablette"],
      "camera": [
        {"type":"wide","note":"plan sur la salle et l'écran"},
        {"type":"insert","note":"tracé de la trajectoire projeté sur la carte"}
      ],
      "lines": [
        "Messieurs, la mission d'aujourd'hui n'est pas un exercice.",
        "Fenêtre: 42 minutes. Décollage 10:30. Retour 11:15.",
        "Communications: Alpha-Seven. Aucune déviation de trajectoire."
      ],
      "duration_est": 180
    },
    {
      "id": "s04-prevol-mecanos-complicite",
      "title": "Inspection pré-vol — 'La main sur le métal'",
      "summary": "Tour de l'avion avec mécanos. Vérifications train, turbines, réservoirs. Complicité pilote-mécano.",
      "description": "Mécanos tachés d'huile, gestes précis. Le pilote pose la main sur la carlingue comme un rituel. Tablette de check-list. Échanges brefs, humour sec.",
      "tags": ["pre-vol","mecanos","complicite","visite-technique"],
      "props": ["tablette_maintenance","clés","gants_noirs","sangles_parachute"],
      "camera": [
        {"type":"walkaround","note":"plan en circonference autour de l'appareil"},
        {"type":"detail","note":"regard dans la turbine, reflet du soleil"},
        {"type":"reaction","note":"échange pilote/mécano, sourire contenu"}
      ],
      "checklist": [
        "train_aterrissage: ok",
        "pneumatique: pression 2.4 bar",
        "fuites_reservoir: none",
        "aile: fixation N-3 ok"
      ],
      "duration_est": 240
    },
    {
      "id": "s05-embarquement-cockpit",
      "title": "Embarquement — Cockpit & checks internes",
      "summary": "Pilote s'installe, vérifielances instruments, casque à la main, communication radio.",
      "description": "Plan serré sur le cockpit : manettes, HUD, tableau d'instruments. Mise en place du harnais. Visière qui se rabaisse.",
      "tags": ["cockpit","embarquement","HUD","instruments"],
      "props": ["harnais","casque","visiere","manettes"],
      "camera": [
        {"type":"insert","note":"tableau d'instruments"},
        {"type":"POV","note":"vue depuis l'intérieur vers l'avant"}
      ],
      "duration_est": 150
    },
    {
      "id": "s06-decollage-formation",
      "title": "Décollage — Formation",
      "summary": "Poussée, montée, formation serrée. Radio concise, code alpha-sept.",
      "description": "MV du décollage: spatiale, vibrations, montée en formation. Plans extérieurs et intérieurs, communication codée.",
      "tags": ["décollage","formation","radio","aerien"],
      "props": ["apres_burner","contrails","formation_led"],
      "camera": [
        {"type":"aerial","note":"plans drone/chasers sur formation"},
        {"type":"cockpit_internal","note":"mains sur manche, HUD actif"}
      ],
      "duration_est": 210
    },
    {
      "id": "s07-mission-rasemode-montagne",
      "title": "Mission — Rase-mottes / Montagne / Escadrille",
      "summary": "Différents modes de mission : rase-motte, montagneux, escadrille serrée.",
      "description": "Séquences type: rase-motte au-dessus de la mer, passage en canyon, accompagnement d'escadrille. Consignes sécurité, redondances radio.",
      "tags": ["mission","rase-motte","montagne","escadrille"],
      "props": ["munition_dummy","flaps","countermeasures"],
      "camera": [
        {"type":"lowpass","note":"chase cam low pass au ras de l'eau"},
        {"type":"overhead","note":"plan large sur l'escadrille"}
      ],
      "duration_est": 600
    },
    {
      "id": "s08-atterrissage-debrief",
      "title": "Atterrissage & Débrief",
      "summary": "Retour, taxi, débrief rapide, gestes mécanos pour vérifier appareils.",
      "description": "Escorte au parking, mécanos récupèrent données, débrief sec dans salle. Respect du rituel d'après-vol.",
      "tags": ["atterrissage","debrief","post-vol"],
      "props": ["data_recorder","tablette","cafe"],
      "camera": [
        {"type":"wide","note":"arrivée sur le parking"},
        {"type":"interior","note":"débrief sur écran, notes résumées"}
      ],
      "duration_est": 180
    }
  ]
};
